Shopify/javascript

packages/shopify-codemod/README.md
packages/shopify-codemod/test/fixtures/function-to-arrow/basic.input.js
packages/shopify-codemod/test/fixtures/function-to-arrow/basic.output.js
packages/shopify-codemod/test/fixtures/function-to-arrow/this.input.js
packages/shopify-codemod/test/fixtures/function-to-arrow/this.output.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/basic.output.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/bdd.output.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/extra-this.output.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/name-clobbering.output.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/nested.output.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/use-in-test.output.js
packages/shopify-codemod/test/transforms/function-to-arrow.test.js
packages/shopify-codemod/transforms/function-to-arrow.js
packages/shopify-codemod/transforms/mocha-context-to-closure.js

Separate function to arrow transform

---

packages/shopify-codemod/README.md
packages/shopify-codemod/test/fixtures/remove-useless-return-from-test/basic.input.js
packages/shopify-codemod/test/fixtures/remove-useless-return-from-test/basic.output.js
packages/shopify-codemod/test/transforms/remove-useless-return-from-test.test.js
packages/shopify-codemod/transforms/constant-function-expression-to-statement.js
packages/shopify-codemod/transforms/function-to-arrow.js
packages/shopify-codemod/transforms/index.js
packages/shopify-codemod/transforms/mocha-context-to-closure.js
packages/shopify-codemod/transforms/remove-useless-return-from-test.js
packages/shopify-codemod/transforms/ternary-statement-to-if-statement.js

@lemonmade this will save a lot of time when translating test files

Add codemod to remove unneeded returns from test files

---

circle.yml
packages/shopify-codemod/README.md
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/basic.input.js
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/basic.output.js
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/function.input.js
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/function.output.js
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/value.input.js
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/value.output.js
packages/shopify-codemod/test/fixtures/global-reference-to-import/assignment.input.js
packages/shopify-codemod/test/fixtures/global-reference-to-import/assignment.output.js
packages/shopify-codemod/test/fixtures/global-reference-to-import/basic.input.js
packages/shopify-codemod/test/fixtures/global-reference-to-import/basic.output.js
packages/shopify-codemod/test/fixtures/javascripts/app/components/element.coffee
packages/shopify-codemod/test/fixtures/javascripts/app/components/ui_list.coffee
packages/shopify-codemod/test/fixtures/javascripts/app/components/widget.js
packages/shopify-codemod/test/test-helper.js
packages/shopify-codemod/test/transforms/global-assignment-to-default-export.test.js
packages/shopify-codemod/test/transforms/global-reference-to-import.test.js
packages/shopify-codemod/transforms/global-assignment-to-default-export.js
packages/shopify-codemod/transforms/global-reference-to-import.js
packages/shopify-codemod/transforms/utils.js

@lemonmade 
This automatically finds references to global references and translates them to import statements.
It also finds any global variable assignments and translates them to export statements

Add global-assignment-to-default-export and global-reference-to-import

---

packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/directive.input.js
packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/directive.output.js
packages/shopify-codemod/test/fixtures/global-reference-to-import/directive.input.js
packages/shopify-codemod/test/fixtures/global-reference-to-import/directive.output.js
packages/shopify-codemod/test/transforms/global-assignment-to-default-export.test.js
packages/shopify-codemod/test/transforms/global-reference-to-import.test.js
packages/shopify-codemod/transforms/global-assignment-to-default-export.js
packages/shopify-codemod/transforms/global-reference-to-import.js
packages/shopify-codemod/transforms/utils.js

Preserve directives when adding import statement

---

circle.yml
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/contextually-declared-functions.input.js
packages/shopify-codemod/test/fixtures/mocha-context-to-closure/contextually-declared-functions.output.js
packages/shopify-codemod/test/transforms/mocha-context-to-closure.test.js
packages/shopify-codemod/transforms/mocha-context-to-closure.js

Convert this used in this-assigned functions

---

CHANGELOG.md
README.md
react/README.md

This PR adds the changes for the past few versions we forgot to add to the changelog. It also updates the READMEs to fix #7 and #8, and to add Enzyme as a recommended utility for React testing.
cc/ @goodforonefare

Update READMEs and changelog

---

packages/eslint-plugin-shopify/README.md
packages/eslint-plugin-shopify/docs/rules/class-property-semi.md
packages/eslint-plugin-shopify/docs/rules/no-useless-computed-properties.md
packages/eslint-plugin-shopify/docs/rules/require-flow.md
packages/eslint-plugin-shopify/docs/rules/restrict-full-import.md
packages/eslint-plugin-shopify/docs/rules/sinon-no-restricted-features.md
packages/eslint-plugin-shopify/docs/rules/sinon-prefer-meaningful-assertions.md
packages/eslint-plugin-shopify/lib/config/rules/shopify.js
packages/eslint-plugin-shopify/lib/rules/class-property-semi.js
packages/eslint-plugin-shopify/lib/rules/no-useless-computed-properties.js
packages/eslint-plugin-shopify/lib/rules/prefer-early-return.js
packages/eslint-plugin-shopify/lib/rules/restrict-full-import.js
packages/eslint-plugin-shopify/lib/rules/sinon-no-restricted-features.js
packages/eslint-plugin-shopify/lib/rules/sinon-prefer-meaningful-assertions.js
packages/eslint-plugin-shopify/tests/lib/rules/class-property-semi.js
packages/eslint-plugin-shopify/tests/lib/rules/no-useless-computed-properties.js
packages/eslint-plugin-shopify/tests/lib/rules/restrict-full-import.js
packages/eslint-plugin-shopify/tests/lib/rules/sinon-no-restricted-features.js
packages/eslint-plugin-shopify/tests/lib/rules/sinon-prefer-meaningful-assertions.js

I had a bunch of ideas yesterday so I just built them all. Just get to this the you can :) @GoodForOneFare

Additional ESLint rules

---

README.md
jquery/README.md
legacy/README.md
packages/eslint-plugin-shopify/README.md
packages/eslint-plugin-shopify/docs/rules/no-useless-computed-properties.md
packages/eslint-plugin-shopify/docs/rules/prefer-class-properties.md
packages/eslint-plugin-shopify/index.js
packages/eslint-plugin-shopify/lib/config/esnext.js
packages/eslint-plugin-shopify/lib/config/rules/shopify.js
packages/eslint-plugin-shopify/lib/rules/prefer-class-properties.js
packages/eslint-plugin-shopify/tests/lib/rules/prefer-class-properties.js
react/README.md

One more rule! Also updated some docs for all the new rules.
cc/ @GoodForOneFare

Add prefer-class-properties rule

---

packages/eslint-plugin-shopify/lib/rules/jquery-dollar-sign-reference.js
packages/eslint-plugin-shopify/tests/lib/rules/jquery-dollar-sign-reference.js

Allow null for jquery reference

---

README.md
packages/eslint-plugin-shopify/lib/config/esnext.js

Remove class-properties preference

---

packages/shopify-codemod/README.md
packages/shopify-codemod/test/fixtures/remove-empty-returns/arrow-functions.input.js
packages/shopify-codemod/test/fixtures/remove-empty-returns/arrow-functions.output.js
packages/shopify-codemod/test/fixtures/remove-empty-returns/function-declarations.input.js
packages/shopify-codemod/test/fixtures/remove-empty-returns/function-declarations.output.js
packages/shopify-codemod/test/fixtures/remove-empty-returns/function-expressions.input.js
packages/shopify-codemod/test/fixtures/remove-empty-returns/function-expressions.output.js
packages/shopify-codemod/test/transforms/remove-addeventlistener-returns.test.js
packages/shopify-codemod/test/transforms/remove-empty-returns.test.js
packages/shopify-codemod/transforms/remove-empty-returns.js

combined transforms and corrected test cases
updated readme instructions to reflect setup
uses matchLast util and cleaned up dependencies + test case naming conventions
added sanity checks

removes redundant empty returns

---

packages/eslint-plugin-shopify/lib/config/rules/stylistic-issues.js

eslint spaced-comment: Allow sprockets directives

---

CHANGELOG.md
packages/esify/index.js
packages/shopify-codemod/README.md
packages/shopify-codemod/test/fixtures/add-missing-parseint-radix/basic.input.js
packages/shopify-codemod/test/fixtures/add-missing-parseint-radix/basic.output.js
packages/shopify-codemod/test/transforms/add-missing-parseint-radix.test.js
packages/shopify-codemod/transforms/add-missing-parseint-radix.js

Fixes #117. Does what it says on the tin.
cc/ @fandy

Add missing radix transform

---

CHANGELOG.md
packages/esify/index.js
packages/shopify-codemod/README.md
packages/shopify-codemod/test/fixtures/empty-func-to-lodash-noop/basic.input.js
packages/shopify-codemod/test/fixtures/empty-func-to-lodash-noop/basic.output.js
packages/shopify-codemod/test/fixtures/empty-func-to-lodash-noop/declaration.input.js
packages/shopify-codemod/test/fixtures/empty-func-to-lodash-noop/declaration.output.js
packages/shopify-codemod/test/fixtures/empty-func-to-lodash-noop/method.input.js
packages/shopify-codemod/test/fixtures/empty-func-to-lodash-noop/method.output.js
packages/shopify-codemod/test/transforms/empty-func-to-lodash-noop.test.js
packages/shopify-codemod/transforms/empty-func-to-lodash-noop.js

Replace empty functions with _.noop

---

CHANGELOG.md
README.md
packages/esify/lib/index.js

Remove dash-casing in esify

---

packages/esify/lib/codemod.js
packages/shopify-codemod/docs/arguments-to-args-spread.md
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/basic.input.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/basic.output.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/nested-iife.input.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/nested-iife.output.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/reuse-spread-name.input.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/reuse-spread-name.output.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/sanity.input.js
packages/shopify-codemod/test/fixtures/arguments-to-args-spread/sanity.output.js
packages/shopify-codemod/test/transforms/arguments-to-args-spread.test.js
packages/shopify-codemod/transforms/arguments-to-args-spread.js

Way trickier than it sounds due to IIFE scope quirks.
/cc @lemonmade, @fandy, @justinthec

Add `args` spread argument to functions that reference `arguments`

---

packages/shopify-codemod/README.md

Update README to include doc generation behaviour

---

CHANGELOG.md

@justinthec I wrote this up real quick-like.  Can you check for typos, omissions, inaccuracies, please?

v12.3.3 changelog

---

CHANGELOG.md
packages/babel-preset-shopify/README.md
packages/babel-preset-shopify/index.js
packages/babel-preset-shopify/react.js
packages/esify/README.md
packages/esify/lib/decaf.js
packages/eslint-plugin-shopify/README.md
packages/eslint-plugin-shopify/docs/rules/prefer-twine.md
packages/eslint-plugin-shopify/index.js
packages/eslint-plugin-shopify/lib/config/esnext.js
packages/eslint-plugin-shopify/lib/config/mocha.js
packages/eslint-plugin-shopify/lib/config/react.js
packages/eslint-plugin-shopify/lib/config/rules/shopify.js
packages/eslint-plugin-shopify/lib/rules/prefer-twine.js
packages/eslint-plugin-shopify/tests/lib/rules/prefer-twine.js

Fixes a bunch of small issues.

Issue squashing

---

CHANGELOG.md
packages/shopify-codemod/test/fixtures/avoid-returning-unused-results/basic.input.js
packages/shopify-codemod/test/fixtures/avoid-returning-unused-results/basic.output.js
packages/shopify-codemod/transforms/avoid-returning-unused-results.js

Fix avoid-returning-unused-results edges

---

packages/eslint-plugin-shopify/lib/config/rules/babel.js
packages/shopify-codemod/test/transforms/global-assignment-to-default-export.test.js
packages/shopify-codemod/test/transforms/global-reference-to-import.test.js
packages/shopify-codemod/transforms/assert/assert-false-to-assert-fail.js
packages/shopify-codemod/transforms/assert/assert-to-assert-ok.js
packages/shopify-codemod/transforms/assert/call-count-equals-to-assert-called.js
packages/shopify-codemod/transforms/assert/called-method-to-assert-called.js
packages/shopify-codemod/transforms/assert/called-with-methods-to-assert-called-with.js
packages/shopify-codemod/transforms/assert/equality-comparisons-to-assertions.js
packages/shopify-codemod/transforms/assert/falsy-called-method-to-assert-not-called.js
packages/shopify-codemod/transforms/assert/move-literals-to-expected-argument.js
packages/shopify-codemod/transforms/assert/negated-assert-ok-to-assert-not-ok.js
packages/shopify-codemod/transforms/assert/utils.js
packages/shopify-codemod/transforms/coffeescript-range-output-to-helper.js
packages/shopify-codemod/transforms/coffeescript-soak-to-condition.js
packages/shopify-codemod/transforms/constant-function-expression-to-statement.js
packages/shopify-codemod/transforms/constructor-literal-assignment-to-class-property.js
packages/shopify-codemod/transforms/convert-default-export-objects-to-named-exports.js
packages/shopify-codemod/transforms/global-assignment-to-default-export.js
packages/shopify-codemod/transforms/global-identifier-to-import.js
packages/shopify-codemod/transforms/global-reference-to-import.js
packages/shopify-codemod/transforms/mocha-context-to-closure.js
packages/shopify-codemod/transforms/mocha-context-to-global-reference.js
packages/shopify-codemod/transforms/remove-addeventlistener-returns.js
packages/shopify-codemod/transforms/rename-property.js

@lemonmade for consistency with the object dangle rules

Always commas for multiline function params

---

README.md
react/README.md
testing/README.md

Hey team. I got the ball rolling with a possible outline for a JS testing guide. Who can iterate on this branch? @tylerball @lemonmade @tessalt @m-ux 
I suggest we a) Get a first version complete before bringing in more FED for review and b) Focus on just writing down what we currently do most of the time rather than advancing the state of the art.
This doc can probably provide a great starting point and I've already lifted some stuff from it: https://github.com/Shopify/shopify/wiki/Admin-Testing

Testing guide

---

packages/esify/lib/codemod.js
packages/esify/lib/eslint.js

Attempt to load local eslint and process with --fix. 
Fixes #185 
@lemonmade @GoodForOneFare

Fix esify eslint

---

CHANGELOG.md
package.json
packages/chai-jscodeshift/index.js
packages/eslint-plugin-shopify/lib/config/rules/best-practices.js
packages/eslint-plugin-shopify/lib/config/rules/stylistic-issues.js
packages/eslint-plugin-shopify/package.json
packages/shopify-codemod/transforms/global-assignment-to-default-export.js

I don't believe there are any breaking changes. I tested esify quickly, it seems to work fine, and fixes more errors 👍 
@lemonmade @GoodForOneFare

Bump eslint version

---

packages/eslint-plugin-shopify/lib/config/esnext.js
packages/eslint-plugin-shopify/lib/config/rules/ava.js
packages/eslint-plugin-shopify/lib/config/rules/babel.js
packages/eslint-plugin-shopify/lib/config/rules/flowtype.js
packages/eslint-plugin-shopify/lib/config/rules/import.js
packages/eslint-plugin-shopify/lib/config/rules/lodash.js
packages/eslint-plugin-shopify/lib/config/rules/react.js
packages/eslint-plugin-shopify/package.json

Update eslint plugins

---

README.md
testing/README.md

Caught a few minor typos while reading through this, figured I would go ahead and fix them 😸

Fix minor typos

---

README.md

Fix up README.md links :memo:

---

README.md

Was reading through your documentation and thought this could be a positive change.

[fix] Removed the word "ugly" from otherwise fantastic documentation

---

README.md

https://github.com/Shopify/javascript/issues/263

Loosen the rule on instance methods using `this`
