Shopify/javascript

README.md, package.json, packages/eslint-config-shopify/.eslintrc, packages/eslint-config-shopify/core/index.js, packages/eslint-config-shopify/es6/index.js, packages/eslint-config-shopify/package.json, packages/eslint-config-shopify/react/index.js, packages/eslint-config-shopify/rules/best-practices.js, packages/eslint-config-shopify/rules/ecmascript-6.js, packages/eslint-config-shopify/rules/node.js, packages/eslint-config-shopify/rules/stylistic-issues.js, packages/eslint-plugin-shopify/index.js, packages/generator-eslint-shopify/.eslintrc
This PR does most of the required updates for ESLint 2.0, including:
- Added configurations for new rules and removed deprecated/ deleted rules (and updated the README accordingly).
- Updated the configs for the new `parserOptions` key.
- Removed the `rulesConfig` for the plugin.
- Did all the necessary dependency updates.
I omitted one important thing to keep this PR easy to review: ESLint allows us to bundle our config with our plugin, which will allow us to basically get the required packages down to 1. The config for consuming projects looks a bit worse (`{"extends": "plugin:shopify/es6"}` instead of `{"extends": "shopify"}`), but I think that's an acceptable tradeoff. If no one has any objections, I will do that work in an additional PR.
cc/ @Shopify/fed @bouk
=> ESLint 2.0, Round 1

CONTRIBUTING.md, README.md, package.json, packages/eslint-config-shopify/.eslintrc, packages/eslint-config-shopify/README.md, packages/eslint-plugin-shopify/.eslintrc, packages/eslint-plugin-shopify/README.md, packages/eslint-plugin-shopify/index.js, packages/eslint-plugin-shopify/lib/config/.eslintrc, packages/eslint-plugin-shopify/lib/config/core/index.js, packages/eslint-plugin-shopify/lib/config/es5/index.js, packages/eslint-plugin-shopify/lib/config/esnext/index.js, packages/eslint-plugin-shopify/lib/config/react/index.js, packages/eslint-plugin-shopify/lib/config/rules/best-practices.js, packages/eslint-plugin-shopify/lib/config/rules/ecmascript-6.js, packages/eslint-plugin-shopify/lib/config/rules/legacy.js, packages/eslint-plugin-shopify/lib/config/rules/node.js, packages/eslint-plugin-shopify/lib/config/rules/possible-errors.js, packages/eslint-plugin-shopify/lib/config/rules/react.js, packages/eslint-plugin-shopify/lib/config/rules/shopify.js, packages/eslint-plugin-shopify/lib/config/rules/strict-mode.js, packages/eslint-plugin-shopify/lib/config/rules/stylistic-issues.js, packages/eslint-plugin-shopify/lib/config/rules/variables.js, packages/eslint-plugin-shopify/package.json, packages/generator-eslint-shopify/.eslintrc, packages/generator-eslint-shopify/package.json, packages/generator-eslint-shopify/src/app/index.js, packages/generator-eslint-shopify/test/src/app/index.test.js
This PR uses the new features in ESLint 2.0 to update the `eslint-plugin-shopify` to serve our shared config in addition to our custom rules. It also moves the react plugin and babel parser to be dependencies of the plugin. What this means is that installation is now considerably simpler — you just need to `npm install eslint eslint-plugin-shopify --save-dev` and add an `.eslintrc` file that points to the plugin's configs.
As mentioned in the previous PR, the config name (in the `eslintrc "extends"` field)  is a bit more complex — `shopify` becomes `plugin:shopify/esnext`, `shopify/react` becomes `plugin:shopify/react`, and `shopify/es5` becomes `plugin:shopify/es5`. A small price to pay for simpler setup and package structure, I think. The generator has also been updated to generate …
=> Consolidate plugin and config

packages/eslint-plugin-shopify/lib/config/rules/shopify.js
@lemonmade I think this is better enforced on a per-project basis, and I find myself disabling it anyways
=> Don't require flow

circle.yml, package.json, packages/eslint-plugin-shopify/package.json, packages/generator-eslint-shopify/package.json, packages/shopify-codemod/package.json, packages/shopify-codemod/transforms/constant-function-expression-to-statement.js, packages/shopify-codemod/transforms/function-to-arrow.js, packages/shopify-codemod/transforms/index.js, packages/shopify-codemod/transforms/mocha-context-to-closure.js, packages/shopify-codemod/transforms/ternary-statement-to-if-statement.js, script/check, script/test
This PR moves all the dev dependencies to the root. This makes it so we don't have to download multiple versions of some enormous packages (Babel is particularly bad on this). The tests scripts were all updated so they can be run from the individual packages, as well.
cc/ @bouk
=> Put all dev dependencies at the root

packages/shopify-codemod/README.md, packages/shopify-codemod/test/fixtures/conditional-assign-to-if-statement/assign-to-other-identifier.input.js, packages/shopify-codemod/test/fixtures/conditional-assign-to-if-statement/assign-to-other-identifier.output.js, packages/shopify-codemod/test/fixtures/conditional-assign-to-if-statement/conditional-and-assignments.input.js, packages/shopify-codemod/test/fixtures/conditional-assign-to-if-statement/conditional-and-assignments.output.js, packages/shopify-codemod/test/fixtures/conditional-assign-to-if-statement/conditional-or-assignments.input.js, packages/shopify-codemod/test/fixtures/conditional-assign-to-if-statement/conditional-or-assignments.output.js, packages/shopify-codemod/test/transforms/conditional-assign-to-if-statement.test.js, packages/shopify-codemod/transforms/conditional-assign-to-if-statement.js
This transforms vanilla expression statements.  Conditional assignments that return a value, or that immediately call into the assigned value will be handled by subsequent PRs.
/cc @lemonmade @bouk
=> Transform conditional assignments to `if` blocks

packages/shopify-codemod/README.md, packages/shopify-codemod/test/fixtures/mocha-context-to-global-references/rename.input.js, packages/shopify-codemod/test/fixtures/mocha-context-to-global-references/rename.output.js, packages/shopify-codemod/test/fixtures/mocha-context-to-global-references/replace.input.js, packages/shopify-codemod/test/fixtures/mocha-context-to-global-references/replace.output.js, packages/shopify-codemod/test/transforms/mocha-context-to-global-references.test.js, packages/shopify-codemod/transforms/mocha-context-to-global-references.js, packages/shopify-codemod/transforms/remove-useless-return-from-test.js, packages/shopify-codemod/transforms/utils.js
This PR adds a new transform to handle the renaming of some things that are injected into the test context (`spy`/ `stub`/ `clock` etc) to use a global defined for the tests instead. The codemod allows you to define these as either replacing the whole member expression (`this.clock -> testClock`) or to just replace the object in the member expression with the test global (`this.spy -> sinon.spy`).
cc/ @goodforonefare
=> Add mochaContextToGlobalReferences codemod

packages/shopify-codemod/test/fixtures/mocha-context-to-closure/contextually-declared-functions.input.js, packages/shopify-codemod/test/fixtures/mocha-context-to-closure/contextually-declared-functions.output.js, packages/shopify-codemod/transforms/mocha-context-to-closure.js
Previously, `handleContext` would try to transform *any* function inside a suite.  This broke when suites invoked non-Mocha functions (e.g., `itDoesNotRemoveTheErrorClass` in `error_remover_test.coffee`).
/cc @lemonmade
=> Don't try to transform non-Mocha functions

packages/shopify-codemod/test/fixtures/remove-useless-return-from-test/basic.input.js, packages/shopify-codemod/test/fixtures/remove-useless-return-from-test/basic.output.js, packages/shopify-codemod/transforms/remove-useless-return-from-test.js
Gets rid of `return;` lines from Mocha functions (these were breaking tests like `amount_validation_test.coffee`).
/cc @lemonmade
=> Strip argless returns if they're the last line of a Mocha function

packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/both-variables.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/both-variables.output.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/end-variable.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/end-variable.output.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/exclusive.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/exclusive.output.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/inclusive.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/inclusive.output.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/similar-cases.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/similar-cases.output.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/start-variable.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/start-variable.output.js, packages/shopify-codemod/test/transforms/coffeescript-range-output-to-helper.test.js, packages/shopify-codemod/transforms/coffeescript-range-output-to-helper.js, packages/shopify-codemod/transforms/remove-useless-return-from-test.js, packages/shopify-codemod/transforms/utils.js
This PR adds a transform that changes all of the gross CoffeeScript-range-generated garbage into a reference to a global function. This transform will need to happen before the global reference to import one when run via edify. I couldn't think of a nice way to make this generic (so it could be used by non-Shopify code), but I figured that wasn't a big deal for now.
cc/ @GoodForOneFare
=> Use a range-generating function rather than CoffeeScript output

packages/shopify-codemod/test/fixtures/function-to-arrow/method.input.js, packages/shopify-codemod/test/fixtures/function-to-arrow/method.output.js, packages/shopify-codemod/test/fixtures/function-to-arrow/return-without-argument.input.js, packages/shopify-codemod/test/fixtures/function-to-arrow/return-without-argument.output.js, packages/shopify-codemod/test/transforms/function-to-arrow.test.js, packages/shopify-codemod/transforms/function-to-arrow.js
Fixes `function-to-arrow` by:
- Ignoring class methods
- (I know that `transform-class-properties` is enabled, but, eh, stage 1)
- Handling functions with argument-less `return`s
/cc @lemonmade
=> Fix function to arrow

packages/eslint-plugin-shopify/README.md, packages/eslint-plugin-shopify/docs/rules/class-property-semi.md, packages/eslint-plugin-shopify/docs/rules/jquery-dollar-sign-reference.md, packages/eslint-plugin-shopify/docs/rules/no-useless-computed-properties.md, packages/eslint-plugin-shopify/docs/rules/prefer-early-return.md, packages/eslint-plugin-shopify/docs/rules/require-flow.md, packages/eslint-plugin-shopify/docs/rules/restrict-full-import.md, packages/eslint-plugin-shopify/docs/rules/sinon-no-restricted-features.md, packages/eslint-plugin-shopify/docs/rules/sinon-prefer-meaningful-assertions.md, packages/eslint-plugin-shopify/index.js, packages/eslint-plugin-shopify/lib/config/rules/shopify.js, packages/eslint-plugin-shopify/lib/rules/class-property-semi.js, packages/eslint-plugin-shopify/lib/rules/jquery-dollar-sign-reference.js, packages/eslint-plugin-shopify/lib/rules/no-useless-computed-properties.js, packages/eslint-plugin-shopify/lib/rules/prefer-early-return.js, packages/eslint-plugin-shopify/lib/rules/restrict-full-import.js, packages/eslint-plugin-shopify/lib/rules/sinon-no-restricted-features.js, packages/eslint-plugin-shopify/lib/rules/sinon-prefer-meaningful-assertions.js, packages/eslint-plugin-shopify/tests/.eslintrc.js, packages/eslint-plugin-shopify/tests/lib/rules/binary-assignment-parens.js, packages/eslint-plugin-shopify/tests/lib/rules/class-property-semi.js, packages/eslint-plugin-shopify/tests/lib/rules/jquery-dollar-sign-reference.js, packages/eslint-plugin-shopify/tests/lib/rules/no-useless-computed-properties.js, packages/eslint-plugin-shopify/tests/lib/rules/prefer-early-return.js, packages/eslint-plugin-shopify/tests/lib/rules/require-flow.js, packages/eslint-plugin-shopify/tests/lib/rules/restrict-full-import.js, packages/eslint-plugin-shopify/tests/lib/rules/sinon-no-restricted-features.js, packages/eslint-plugin-shopify/tests/lib/rules/sinon-prefer-meaningful-assertions.js
This PR adds two ESLint rules:
1. `jquery-dollar-sign-reference` forces you to prefix references with `$` when they definitely refer to jQuery objects (and prevents you from prefixing with `$` if it definitely does not refer to a jQuery object).
2. `prefer-early-return` forces you to use an early return instead of nesting an entire function body in a conditional expression without an alternate.
Let me know if you want me to break this into two PRs, I figured I'd add them both at once but we can at list split it for ease of review.
cc/ @GoodForOneFare @bouk
=> Add some ESLint rules

.gitignore, packages/esify/README.md, packages/esify/bin/esify, packages/esify/index.js, packages/esify/package.json, packages/shopify-codemod/package.json
This adds `esify` as an actual project into the JS repo, and moves things around so that it can work by being installed globally and running `esify path/to/file.coffee` from the root of the Shopify repo.
cc/ @GoodForOneFare @bouk
=> Make esify an installable binary

packages/eslint-plugin-shopify/docs/rules/no-fully-static-classes.md, packages/eslint-plugin-shopify/lib/rules/no-fully-static-classes.js, packages/eslint-plugin-shopify/package.json, packages/eslint-plugin-shopify/tests/lib/rules/no-fully-static-classes.js
This PR adds a rule to prevent the use of classes with only static members. I see this a bunch, particularly from people that aren't really used to JavaScript, and it drives me completely crazy (obviously, an object literal would be better since it avoids the one level of extra object creation).
cc/ @GoodForOneFare @bouk
=> Add no-fully-static-classes rule

packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/loop.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/loop.output.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/similar-cases.input.js, packages/shopify-codemod/test/fixtures/coffeescript-range-output-to-helper/similar-cases.output.js, packages/shopify-codemod/transforms/coffeescript-range-output-to-helper.js
I was using a pretty shitty heuristic to figure out functions that looked like the output of CoffeeScript ranges before (specifically, the `loop.input.js` file was not converting before). This PR uses a better set of criteria in order to make that decision.
cc/ @GoodForOneFare
=> Fix: CoffeeScript range now works without defined i

packages/esify/index.js, packages/shopify-codemod/test/fixtures/strip-template-literal-parenthesis/basic.input.js, packages/shopify-codemod/test/fixtures/strip-template-literal-parenthesis/basic.output.js, packages/shopify-codemod/test/transforms/strip-template-literal-parenthesis.test.js, packages/shopify-codemod/transforms/strip-template-literal-parenthesis.js
Decaf wraps *every* template string with parenthesis.  There's nowhere in the Shopify codebase that requires this.
This transform relies on odd behaviour to strip out parenthesis; I'm guessing that recast sees a new property on the node and this forces a (good) destructive change.  There's an unsupported `Node#parenthesizedExpression` property that *may* make this less haphazard, but I couldn't get it to work any more effectively than this solution.
/cc @lemonmade
=> Strip unnecessary parenthesis from template strings

packages/esify/README.md, packages/esify/bin/esify, packages/esify/index.js, packages/esify/package.json
This PR lets other projects use `esify` by removing some values that were hardcoded to Shopify, and allowing custom options to be set using a configuration file.
cc/ @bouk @GoodForOneFare @tylerball
=> Make `esify` usable by other projects

packages/esify/index.js, packages/shopify-codemod/README.md, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/assignment.input.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/assignment.output.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/basic.input.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/basic.output.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/function-calls.input.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/function-calls.output.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/logical-expressions.input.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/logical-expressions.output.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/other-parents.input.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/other-parents.output.js, packages/shopify-codemod/test/transforms/coffeescript-soak-to-condition.test.js, packages/shopify-codemod/transforms/coffeescript-soak-to-condition.js
This PR adds a transform to make the output of CoffeeScript's `?` operator a lot cleaner. The output of that operator quickly becomes a complex, nested ternary operator, so this will be a big improvement.
cc/ @GoodForOneFare @bouk
=> Add CoffeeScript soak transform

packages/chai-jscodeshift/index.js, packages/chai-jscodeshift/test/index.test.js, packages/shopify-codemod/test/fixtures/global-reference-to-import/multiple-matches/basic-invalid.input.js, packages/shopify-codemod/test/fixtures/global-reference-to-import/multiple-matches/basic-valid.input.js, packages/shopify-codemod/test/fixtures/global-reference-to-import/multiple-matches/basic-valid.output.js, packages/shopify-codemod/test/fixtures/global-reference-to-import/multiple-matches/nested-invalid.input.js, packages/shopify-codemod/test/fixtures/javascripts/app/components/invalid-multiple-two.js, packages/shopify-codemod/test/fixtures/javascripts/app/components/invalid_multiple_one.coffee, packages/shopify-codemod/test/fixtures/javascripts/app/components/invalid_multiple_three.coffee, packages/shopify-codemod/test/fixtures/javascripts/app/components/nested/invalid-multiple-three.js, packages/shopify-codemod/test/fixtures/javascripts/app/components/valid-multiple-match.js, packages/shopify-codemod/test/fixtures/javascripts/app/components/valid_multiple_match.coffee, packages/shopify-codemod/test/transforms/global-reference-to-import.test.js, packages/shopify-codemod/transforms/global-reference-to-import.js
Fixes #59. This PR improves `global-reference-to-import` to allow duplicate import sources in one case: when there are exactly two matches, and they are an equivalent JS/ CS pair (same directory, JS name is dash-cased). I also added another assertion to `chai-jscodeshift` to expect a thrown error when transforming a particular fixture.
cc/ @bouk @GoodForOneFare @fandy
=> Prefer equivalent JavaScript file for multiple global-to-import matches

packages/esify/index.js
This PR moves the transforms around a little bit to have the stylistic ones at the end, which will hopefully catch and standardize any additional nodes that were added in subsequent transforms.
cc/ @bouk @GoodForOneFare @fandy
=> Improve order of transforms

packages/esify/bin/esify
Gets esify to accept multiple input args, e.g., 
```esify app/assets/javascripts/sello/**/*.coffee test/sello-javascripts/**/*.coffee```
I found this very useful while troubleshooting our soak transform problems, but I'm okay with not merging this if it's not generally useful.
/cc @lemonmade @bouk
=> esify now accepts multiple files/globs

packages/esify/README.md, packages/esify/index.js, packages/shopify-codemod/README.md, packages/shopify-codemod/test/fixtures/global-identifier-to-import/basic.input.js, packages/shopify-codemod/test/fixtures/global-identifier-to-import/basic.output.js, packages/shopify-codemod/test/fixtures/remove-useless-return-from-test/iife.input.js, packages/shopify-codemod/test/fixtures/remove-useless-return-from-test/iife.output.js, packages/shopify-codemod/test/transforms/global-identifier-to-import.test.js, packages/shopify-codemod/test/transforms/remove-useless-return-from-test.test.js, packages/shopify-codemod/transforms/coffeescript-range-output-to-helper.js, packages/shopify-codemod/transforms/global-identifier-to-import.js, packages/shopify-codemod/transforms/global-reference-to-import.js, packages/shopify-codemod/transforms/mocha-context-to-global-reference.js, packages/shopify-codemod/transforms/remove-empty-returns.js, packages/shopify-codemod/transforms/remove-useless-return-from-test.js, packages/shopify-codemod/transforms/utils.js
This PR does a few small things, I can unbundle them if it will make it easier to review:
- Adds `global-identifier-to-import` to turn globals (lodash, jQuery, etc) into import statements.
- Made `remove-useless-return-from-test` also remove the IIFE wrapper from the return argument, if present. This was causing some issues with the transforms that depend on scope to do things, like the mocha ones. The bare IIFE also doesn't really make much sense, it's mostly just used for CoffeeScript's everything-is-an-expression madness.
- Rejigged the order a little bit more.
- Made some small updates to the utilities and a few other files.
cc/ @GoodForOneFare @bouk @fandy
=> Minor improvements from a few more translation examples

packages/shopify-codemod/.npmignore, packages/shopify-codemod/README.md, packages/shopify-codemod/bin/create-transform, packages/shopify-codemod/bin/rename-transform, packages/shopify-codemod/transform-cli/create-transform.js, packages/shopify-codemod/transform-cli/rename-transform.js, packages/shopify-codemod/transform-cli/templates/test-suite.js.template, packages/shopify-codemod/transform-cli/templates/transform.js.template, packages/shopify-codemod/transform-cli/transform-management-utils.js
These have made my life easier, so I thought I'd share.  If they're not useful, I'll keep them in my .gitignore :)
`bin/create-transform my-neato-transform` - creates a transform, test file, and `basic` fixture files
`bin/rename-transform my-neato-transform my-coolio-transform` - renames the transform, test, and fixture dir
/cc @lemonmade, @fandy
=> Scripts to create/rename transforms

packages/shopify-codemod/test/fixtures/global-reference-to-import/self-referencing.input.js, packages/shopify-codemod/test/fixtures/global-reference-to-import/self-referencing.output.js, packages/shopify-codemod/test/fixtures/javascripts/app/components/self-referencing.js, packages/shopify-codemod/test/transforms/global-reference-to-import.test.js, packages/shopify-codemod/transforms/global-reference-to-import.js
Fixes #99. Maybe fixes #95. This PR fixes files importing themselves by checking the `expose` directive (so, it must come after the default export transform, which it does), and adds a global cache that I believe will speed up the lookups between transforms.
cc/ @bouk @GoodForOneFare @fandy
=> Improve global to import transform

packages/esify/README.md, packages/esify/index.js, packages/shopify-codemod/README.md, packages/shopify-codemod/test/fixtures/rename-identifier/basic.input.js, packages/shopify-codemod/test/fixtures/rename-identifier/basic.output.js, packages/shopify-codemod/test/fixtures/rename-property/basic.input.js, packages/shopify-codemod/test/fixtures/rename-property/basic.output.js, packages/shopify-codemod/test/transforms/rename-identifier.test.js, packages/shopify-codemod/test/transforms/rename-property.test.js, packages/shopify-codemod/transforms/global-identifier-to-import.js, packages/shopify-codemod/transforms/rename-identifier.js, packages/shopify-codemod/transforms/rename-property.js, packages/shopify-codemod/transforms/utils.js
Fixes #102 and #126. This PR adds two new transforms, `rename-identifier` and `rename-property`, to handle arbitrary renaming of identifiers and member expressions, respectively.
=> Add rename-identifier and rename-property

packages/shopify-codemod/test/fixtures/function-to-arrow/bad-arrow.input.js, packages/shopify-codemod/test/fixtures/function-to-arrow/bad-arrow.output.js, packages/shopify-codemod/test/transforms/function-to-arrow.test.js, packages/shopify-codemod/transforms/function-to-arrow.js
This PR augments `function-to-arrow` to also remove block statements from existing single-return arrow functions, which are generated by other things and aren't currently being handled.
=> Remove block statements for single-return arrow functions

packages/shopify-codemod/test/fixtures/mocha-context-to-closure/dynamic-names.input.js, packages/shopify-codemod/test/fixtures/mocha-context-to-closure/dynamic-names.output.js, packages/shopify-codemod/test/transforms/mocha-context-to-closure.test.js, packages/shopify-codemod/transforms/mocha-context-to-closure.js
Fixes #94. Wasn't checking for computed properties before :(
=> Fix mocha context to closure on computed props

packages/esify/index.js, packages/shopify-codemod/README.md, packages/shopify-codemod/test/fixtures/computed-literal-keys-to-dot-notation/basic.input.js, packages/shopify-codemod/test/fixtures/computed-literal-keys-to-dot-notation/basic.output.js, packages/shopify-codemod/test/fixtures/rename-property/invalid-identifier.input.js, packages/shopify-codemod/test/fixtures/rename-property/invalid-identifier.output.js, packages/shopify-codemod/test/transforms/computed-literal-keys-to-dot-notation.test.js, packages/shopify-codemod/test/transforms/rename-property.test.js, packages/shopify-codemod/transforms/computed-literal-keys-to-dot-notation.js, packages/shopify-codemod/transforms/rename-property.js, packages/shopify-codemod/transforms/utils.js
Fixes #111. This PR cleans up string literal keys that are valid identifiers to use dot notation for member expressions. Also fixed a potential bug in rename-property for renaming a property to a name that is not a valid identifier (unlikely, but whatever, may as well check).
=> Add a computed-literal-keys-to-dot-notation transform

CHANGELOG.md, packages/esify/index.js, packages/shopify-codemod/README.md
This PR updates the missing documentation/ inclusion in the manifest for `convert-default-export-objects-to-named-exports`. It also reworks the changelog a little bit and sets a standard for what I'd like us to do going forward: An `Unreleased` section that we add to for every change, and a link to the relevant PR for every change.
=> Update manifests and improve changelog

packages/eslint-plugin-shopify/lib/rules/jquery-dollar-sign-reference.js, packages/eslint-plugin-shopify/tests/lib/rules/jquery-dollar-sign-reference.js
This PR fixes #106. It handles a couple extra edge cases for jQuery reference detection, including jQuery-looking keys of objects and multi-assignments.
cc/ @fandy
=> Fix jQuery reference edge cases

packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/other-parents.input.js, packages/shopify-codemod/test/fixtures/coffeescript-soak-to-condition/other-parents.output.js, packages/shopify-codemod/transforms/coffeescript-soak-to-condition.js
Fixes #97. This PR updates `coffeescript-soak-to-condition` to understand an additional edge case with soak/ existential operators.
=> Fix existential soak checks

packages/esify/README.md, packages/esify/index.js, packages/esify/package.json
=> Add a simple warning system for common issues

packages/esify/lib/eslint.js, packages/esify/lib/index.js
Fixes https://github.com/Shopify/javascript/issues/162. Using ESLint's public API to run the lint fixes programatically. Seems to improve things for me!
cc/ @GoodForOneFare
=> Fix ESLint resource hogging

CHANGELOG.md, packages/esify/README.md, packages/esify/lib/codemod.js, packages/esify/lib/config.js, packages/shopify-codemod/README.md, packages/shopify-codemod/docs/avoid-returning-unused-resuls.md, packages/shopify-codemod/docs/avoid-returning-useless-expressions.md, packages/shopify-codemod/docs/remove-unused-expressions.md, packages/shopify-codemod/test/fixtures/avoid-returning-unsused-results/basic.input.js, packages/shopify-codemod/test/fixtures/avoid-returning-unsused-results/basic.output.js, packages/shopify-codemod/test/fixtures/avoid-returning-useless-expressions/basic.input.js, packages/shopify-codemod/test/fixtures/avoid-returning-useless-expressions/basic.output.js, packages/shopify-codemod/test/fixtures/remove-unused-expressions/basic.input.js, packages/shopify-codemod/test/fixtures/remove-unused-expressions/basic.output.js, packages/shopify-codemod/test/transforms/avoid-returning-unsused-results.test.js, packages/shopify-codemod/test/transforms/avoid-returning-useless-expressions.test.js, packages/shopify-codemod/test/transforms/remove-unused-expressions.test.js, packages/shopify-codemod/transforms/avoid-returning-unsused-results.js, packages/shopify-codemod/transforms/avoid-returning-useless-expressions.js, packages/shopify-codemod/transforms/remove-unused-expressions.js, packages/shopify-codemod/transforms/utils.js
Fixes https://github.com/Shopify/javascript/issues/115. Sorry for the big PR, I can break it up if people want.
This PR introduces three transforms: `avoid-returning-unused-results`, `avoid-returning-useless-expressions`, and `remove-unused-expressions`. These collectively solve two cases:
1. Returns in callbacks passed to methods that ignore return values.
2. Returns of method calls that always return `undefined`.
It will also help us get rid of unused expressions separate from the results of these transforms, which is really nice.
cc/ @GoodForOneFare @bouk @justinthec
=> Add transforms for killing unecessary returns

packages/shopify-codemod/transform-cli/create-transform.js, packages/shopify-codemod/transform-cli/rename-transform.js, packages/shopify-codemod/transform-cli/templates/documentation.md.template, packages/shopify-codemod/transform-cli/transform-management-utils.js
Addresses: https://github.com/Shopify/javascript/issues/176
When running `bin/create-transform transform-name`:
* `docs/transform-name.md` is created using the template `transform-cli/templates/documentation.md.template`
When running `bin/rename-transform transform-name other-transform-name`:
* `docs/transform-name.md` is renamed to `docs/other-transform-name.md` and has all dash-cased instances of `tranform-name` replaced with `other-transform-name` in its contents.
@GoodForOneFare @lemonmade
=> Add Docs Generation to Helper commands

packages/esify/lib/codemod.js, packages/shopify-codemod/docs/iife-to-ternary-expression.md, packages/shopify-codemod/test/fixtures/iife-to-ternary-expression/basic.input.js, packages/shopify-codemod/test/fixtures/iife-to-ternary-expression/basic.output.js, packages/shopify-codemod/test/fixtures/iife-to-ternary-expression/sanity.input.js, packages/shopify-codemod/test/fixtures/iife-to-ternary-expression/sanity.output.js, packages/shopify-codemod/test/transforms/iife-to-ternary-expression.test.js, packages/shopify-codemod/transforms/iife-to-ternary-expression.js
https://github.com/Shopify/javascript/issues/158
Turns:
```js
(() => {
if (foo) {
return bar;
} else {
return baz;
}
})();
```
into
```js
(() => {
(foo ? bar : baz);
})();
```
~~If there a way I can just modify the body of a `Node` and then return the original `node`?~~
~~When I try~~
```js
let ternaryExpression = j.conditionalExpression(test, consequentIdentifier, alternateIdentifier);
functionBlockStatement.body = [ternaryExpression];
return node;
```
~~I get this error:~~
```
{test: [object Object], consequent: [object Object], alternate: [object Object], loc: null, type: ConditionalExpression, comments: null} does not match type string
```
~~Also should I be using destructuring assignments for the initial search of nodes?~~
@lemonmade @fandy @GoodForOneFare
=> Added IIFE to Ternary transform

packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/fails-on-global-assign-via-array-accessor.input.js, packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/local-non-prototype-assignment.input.js, packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/local-prototype-assignment.input.js, packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/local-prototype-assignment.output.js, packages/shopify-codemod/test/fixtures/global-assignment-to-default-export/prevent-multiple-exports.input.js, packages/shopify-codemod/test/transforms/global-assignment-to-default-export.test.js, packages/shopify-codemod/transforms/global-assignment-to-default-export.js
If `App.Foo = class Foo` is defined, allows in-module assignments to `App.Foo.prototype`.
This clears up the lion's share of `Found multiple exports in a single file, please break up the file first` errors during `esify` (I'll raise a separate issue once I've analyzed the remainder).
It my be possible to fix this in decaf, but I'm putting out this PR because it's already written, and decaf may not fix things 100%.
/cc @lemonmade, @fandy, @justinthec
=> Allow prototype assignments to exported global

README.md
Currently our [`arrow-body-style:as-needed`](http://eslint.org/docs/rules/arrow-body-style#as-needed) rule only allow arrow functions to use block statements when they contain multiple lines.
However when working with an arrow function with a single very long expression, one may be tempted to break it up onto multiple lines using a block statement like so:
```js
body: (body) => {
return (
body.length === 1 &&
(j.Identifier.check(body[0].expression) || j.MemberExpression.check(body[0].expression))
);
},
```
This however will violate the `arrow-body-style:as-needed` rule.
This added guide to the readme provides the correct alternative to not break the rule while still breaking up the long expression onto multiple lines.
@lemonmade
=> Add arrow-body-style guidance for a singular multiline return.

packages/shopify-codemod/test/fixtures/split-return-assignments/sanity.input.js, packages/shopify-codemod/test/fixtures/split-return-assignments/sanity.output.js, packages/shopify-codemod/test/transforms/split-return-assignments.test.js, packages/shopify-codemod/transforms/split-return-assignments.js
/cc @lemonmade, @justinthec.
Fixed #166.
=> Fix invalid finder criteria in split-return-assignments

packages/esify/lib/codemod.js, packages/shopify-codemod/docs/split-if-assignments.md, packages/shopify-codemod/test/fixtures/split-if-assignments/basic.input.js, packages/shopify-codemod/test/fixtures/split-if-assignments/basic.output.js, packages/shopify-codemod/test/transforms/split-if-assignments.test.js, packages/shopify-codemod/transforms/split-if-assignments.js
Fixes #103.  Simplified version of Andy's PR: https://github.com/Shopify/javascript/pull/154.
Rebased, cleaned up, and added docs.  Also removed support for `SequenceExpression`s because I don't see those anywhere in the core codebase.
/cc @lemonmade, @justinthec
=> Splits up assignments in if statement parameters

packages/shopify-codemod/test/fixtures/global-reference-to-import/basic.input.js, packages/shopify-codemod/test/fixtures/global-reference-to-import/basic.output.js, packages/shopify-codemod/test/fixtures/javascripts/app/components/named_exports.js, packages/shopify-codemod/transforms/global-reference-to-import.js
Fixes: https://github.com/Shopify/javascript/issues/184
Given a named export:
```js
'expose Foo.Bar'
export function baz() {}
```
Those referencing it will now go from:
```js
Foo.Bar.baz();
```
to using namespace imports:
```js
import * as Bar from 'path/to/bar';
Bar.baz();
```
**Note:** The runtime of the test is marked as red by `npm test` at 106 ms.
This is almost certainly due to my use of `fs.fileReadSync`. Any alternative suggestions welcome 🙏 
@lemonmade @GoodForOneFare
=> Modify transform to use namespaced import when finding named exports

packages/esify/lib/config.js
@lemonmade for after https://github.com/Shopify/shopify/pull/76142
=> Automatically import Twine for Bindings

packages/eslint-plugin-shopify/package.json
@lemonmade we don't want to have to release a new version for every minor eslint upgrade, so let's only pin the major version
=> Use a looser peerDependencies for eslint-plugin-shopify

CHANGELOG.md, README.md, packages/eslint-plugin-shopify/lib/config/esnext.js, packages/eslint-plugin-shopify/lib/config/rules/babel.js, packages/eslint-plugin-shopify/lib/config/rules/ecmascript-6.js, packages/eslint-plugin-shopify/lib/config/rules/import.js, packages/eslint-plugin-shopify/lib/config/rules/react.js, packages/eslint-plugin-shopify/lib/config/rules/stylistic-issues.js, packages/eslint-plugin-shopify/lib/rules/require-flow.js, packages/eslint-plugin-shopify/tests/lib/rules/require-flow.js, react/README.md
This PR makes a few small JavaScript linting/ styleguide updates:
- Made it so that `require-flow` allows `@flow` to appear in a line comment (which is apparently allowed now).
- Removed the requirement to omit the braces for arrow functions that have only a return statement and updated the guidance for them to suggest (but not require) omitting the braces for simple return-only arrow functions.
- Turned off linting rules that enforced sorting of properties in React components. This was annoying in my experience and doesn't have the granularity to make it work well with class properties.
- Turned off a rule that required you to use a default export when your module exports only one identifier. IMO some modules make more sense as groups of named exports (usually utility-like things), even …
=> Minor linting updates

README.md
The anchor tag at 10.10 was pointing to 10.1
I updated the markdown link and anchor tag.
=> Fixed anchor tag for 10.10 it was pointing to 10.1

packages/eslint-plugin-shopify/lib/config/rules/react.js, react/README.md
This PR updates a few things on the React styleguide:
- Added back a warning for binding in `render`. Given all the performance talk lately, it's nice to encourage not binding so that we don't create extra rendering and we give components the ability to optimize using shallow comparisons of props.
- Recommended importing the things you need from React (`Component`, `PropTypes`, etc), instead of accessing them as properties on `React`.
- Updated recommendation for how to manage components in a folder with multiple subcomponents — do `Component/Component.js`, `Component/Subcomponent.js`, and export using `Component/index.js`, so that you get good file names everywhere and can still get easy imports elsewhere.
cc/ @Shopify/fed @bouk @harismahmood89
=> Minor React styleguide updates

packages/eslint-plugin-shopify/lib/config/rules/ecmascript-6.js
`import/no-duplicates` is better, as it handles Flow and different paths pointing to the same file.
@lemonmade
[More info about import/no-duplicates](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md)
=> Turn off `no-duplicate-imports` rule

packages/babel-preset-shopify/index.js, packages/babel-preset-shopify/node.js, packages/babel-preset-shopify/non-standard-features.js, packages/babel-preset-shopify/package.json, packages/babel-preset-shopify/react.js, packages/babel-preset-shopify/web.js
This PR updates how Shopify's Babel presets work. I know I kind of did this before and we decided not to separate them out so much, but I have some use cases where this makes sense and I feel like it is more in line with our linting configs.
Basically, it works like this:
- There are separate configs for Node, Web, and React projects, where React is totally usable with either of the other two. The default config is just the web config.
- The web config takes options, which it passes on to the `es2015` preset. This allows us to use the `{modules: false}` option for our config, which makes the preset work with Rollup and Webpack 2 tree shaking.
- The node option also takes options: `modules` (just like the web one), and `version` for specifying a desired version of Node. I was using a …
=> Update babel presets

README.md, package.json, packages/babel-preset-shopify/package.json, packages/chai-jscodeshift/test/test-helper.js, packages/esify/package.json, packages/eslint-plugin-shopify/lib/config/all.js, packages/eslint-plugin-shopify/lib/config/ava.js, packages/eslint-plugin-shopify/lib/config/esnext.js, packages/eslint-plugin-shopify/lib/config/flow.js, packages/eslint-plugin-shopify/lib/config/rules/ava.js, packages/eslint-plugin-shopify/lib/config/rules/best-practices.js, packages/eslint-plugin-shopify/lib/config/rules/ecmascript-6.js, packages/eslint-plugin-shopify/lib/config/rules/flowtype.js, packages/eslint-plugin-shopify/lib/config/rules/import.js, packages/eslint-plugin-shopify/lib/config/rules/jsx-a11y.js, packages/eslint-plugin-shopify/lib/config/rules/mocha.js, packages/eslint-plugin-shopify/lib/config/rules/node.js, packages/eslint-plugin-shopify/lib/config/rules/react.js, packages/eslint-plugin-shopify/lib/config/rules/sort-class-members.js, packages/eslint-plugin-shopify/lib/config/rules/stylistic-issues.js, packages/eslint-plugin-shopify/package.json, packages/shopify-codemod/package.json, packages/shopify-codemod/transforms/constructor-literal-assignment-to-class-property.js
This PR updates all of our linting dependencies to their most recent versions and adds the new rules they introduced. Most notably, the following rules now apply:
- Line comments should be above the line they are commenting, not at the end of it (definitely open to discussion, wasn't sure about this one).
- Always include a description when using the `Symbol` function.
- A bunch of spacing-related rules for Flow.
- In Flow, prevent the usage of `Function` as a type (I chose not to restrict `Object` and `any` since I find them to be useful occasionally, not sure about it though).
- Prevent the usage of `done` and returning a promise together in mocha tests.
- Require whitespace around directives, like `'expose Foo'`.
cc/ @Shopify/javascript @bouk thoughts?
=> Update all dependencies

packages/esify/lib/codemod.js, packages/shopify-codemod/docs/split-assignment-sequences.md, packages/shopify-codemod/test/fixtures/split-assignment-sequences/basic.input.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/basic.output.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/ignore-bodyless-sequences.input.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/ignore-bodyless-sequences.output.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/ignore-mismatched-assignment-sources.input.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/ignore-mismatched-assignment-sources.output.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/ignore-return-sequence-assignments.input.js, packages/shopify-codemod/test/fixtures/split-assignment-sequences/ignore-return-sequence-assignments.output.js, packages/shopify-codemod/test/transforms/split-assignment-sequences.test.js, packages/shopify-codemod/transforms/remove-unused-expressions.js, packages/shopify-codemod/transforms/split-assignment-sequences.js
`decaf` takes stuff like `{@foo, @bar} = opts` and turns it into a sequence like `foo = opts.food, bar = opts.bar, opts`.  This PR:
* Converts each assignment to its own expression
* Removes the trailing `opts`
Note, I haven't handled some edge cases because they have no value to Shopify's current codebase:
* Transforming `return foo = opts.foo, opts` to `foo = opts.foo; return opts`
* Checking that all assigned fields are identifiers with a name matching their source property
Please review @lemonmade, @TylerHorth
=> Split up sequence assignments generated by decaf

packages/esify/lib/decaf.js
Adds some really verbose warnings about for loop conversions.  I think the wording needs a lot of work.
Sample output:
Please review: @lemonmade, @TylerHorth
=> Warn about `for...in`->`for...Object.entries`-style mismatch & null guards

packages/esify/lib/config.js, packages/shopify-codemod/test/fixtures/split-return-assignments/inline.output.js, packages/shopify-codemod/test/test-helper.js
Makes `esify` generate parens for single argument arrow functions.  As Admin's linting config mandates parens, this'll make conversion a little easier.
This is achieved by passing around the `arrowParensAlways` option that [I added to `recast`](https://github.com/benjamn/recast/pull/288).  Go me.
Fixes #167 
Please review: @TylerHorth 
cc @lemonmade
=> Recast now adds arrow parens to single arg functions

node/README.md
This PR documents what versions of Node.js we expect people to use. I think it's pretty pragmatic, but let me know if you feel we should be recommending something else, or if there are additional cases where other versions might be appropriate that I have not documented here.
cc/ @Shopify/javascript
=> Document our Node.js version strategy

README.md, packages/babel-preset-shopify/README.md, packages/eslint-plugin-shopify/README.md
Closes https://github.com/Shopify/javascript/issues/253
This PR adds instructions for using Yarn to install some deps.
=> Added guides for using Yarn to install deps

README.md
Reasons:
- Somewhat defensible: mostly better performance, not Safari ([a test with `NodeList`](https://jsperf.com/spread-syntax-vs-array-from-with-nodelist), [a test with jQuery object](https://jsperf.com/spread-syntax-vs-array-from-with-jquery-object), and [a chart](https://jsperf.com/set-iterator-vs-foreach/4)) but we are talking high operations a second so not sure it is a noticeable difference
- Brevity
- Subjective: easier to read, I prefer it
Also updated mentions of spread operator to spread syntax, as it is not an operator.
@Shopify/javascript
=> Add spread rule for iterable objects

testing/README.md
Revising the guide to add more information on Karma, Jest and generating test coverage.
I think the recommendation for Teaspoon is out of date since there are a bunch of drawbacks compared to Karma and Jest. I've successfully worked with @macdonaldr93 and a bunch of other FEDS to move existing projects off of Teaspoon and onto Karma which enabled easier testing and code coverage to be generated.
=> Update JS testing guide to include Jest and info on generating coverage

coffeescript/README.md, coffeescript/coffeelint.json
I’ve been asked to shut down https://github.com/Shopify/CoffeeScript-Style-Guide if it’s not being used. It’s not _really_ but I think we should preserve this content for anybody updating legacy CoffeeScript which still, unfortunately, exists.
Other than the warning at the top, all of this is directly ported from the CofeeScript-Style-Guide repo unchanged.
I know all this stuff is going to eventually get cleaned up and moved elsewhere, but for the time-being this felt like the best home. Lmk if you disagree.
=> Add legacy CoffeeScript guide

README.md
This updates rule 10.2 following the change in https://github.com/Shopify/eslint-plugin-shopify/pull/188 allowing arrow function expressions.
=> Update 10.2 as per func-style allowArrowFunction

README.md
IMO default exports confuse things by creating 2 ways to import/export components while offering no perceivable benefit/advantage.
I believe a world with only named imports would be more consistent, but I’m happy to hear and and all thoughts and opinions that are different (that's what PRs are for!).
`polaris-react` already enforces they not be used with the `import/no-default-export` rule (https://github.com/Shopify/polaris-react/issues/1959) and web-admin also shies away from them. 
Let's document it and make it official, OR be more specific about when and how they're used so we're consistent across repos.
=> Discourage the use of default exports
